// example/src/function-binary/valid-09-binary-in-cn-function/example.tsx
import { clsx as cn } from 'clsx';

// Simulate dynamic values that might come from props or state
const isError = false;

/**
 * ✅ Valid: Binary in cn() function
 * @validClasses [flex, text-red-500]
 */
export function BinaryInCnFunction() {
	return <div className={cn('flex', isError && 'text-red-500')}>Binary in cn()</div>;
}

// Mock function declarations

// example/src/vue/array-binary/error-02-multiple-classes/example.vue
<script setup lang="ts">
import { clsx as cn } from 'clsx';

const isError = true;

// ❌ Invalid: Binary with multiple classes, one invalid
// @invalidClasses [invalid-class]
// @validClasses [flex, text-red-500, font-bold]
</script>

<template>
  <div :class="cn(['flex', isError && 'text-red-500 invalid-class font-bold'])">
  			Binary with multiple classes
  		</div>
</template>
