// example/src/vue/object-static/valid-16-object-mixed-with-array/example.vue
<script setup lang="ts">
import clsx from 'clsx';

const isActive = true;

// ✅ Valid: Mix of object and array
// @validClasses [flex, items-center, justify-center, bg-blue-500]
</script>

<template>
  <div
  			:class="clsx(['flex', 'items-center'], {
  				'justify-center': true,
  				'bg-blue-500': isActive
  			})">
  			Mixed with array
  		</div>
</template>

// example/src/function-static/valid-12-classnames-function/example.tsx
import classNames from 'classnames';

/**
 * ✅ Valid: Using classNames() function
 * @validClasses [flex, items-center, justify-center]
 */
export function UsingClassNamesFunction() {
	return (
		<div className={classNames('flex', 'items-center', 'justify-center')}>
			Using classNames function
		</div>
	);
}
