// example/src/vue/array-binary/error-02-multiple-classes/example.vue
<script setup lang="ts">
import { clsx as cn } from 'clsx';

const isError = true;

// ❌ Invalid: Binary with multiple classes, one invalid
// @invalidClasses [invalid-class]
// @validClasses [flex, text-red-500, font-bold]
</script>

<template>
  <div :class="cn(['flex', isError && 'text-red-500 invalid-class font-bold'])">
  			Binary with multiple classes
  		</div>
</template>

// example/src/array-ternary/error-05-multiple-ternary-invalid/example.tsx
import { clsx as cn } from 'clsx';

/**
 * ❌ Invalid: Multiple ternary expressions with invalid classes
 * @invalidClasses [invalid-active, invalid-disabled]
 * @validClasses [flex, bg-gray-500, text-black]
 */

const isActive = true;
const isDisabled = false;

export function ArrayMultipleTernaryInvalid() {
	return (
		<div
			className={cn([
				'flex',
				isActive ? 'invalid-active' : 'bg-gray-500',
				isDisabled ? 'invalid-disabled' : 'text-black'
			])}>
			Multiple ternary with invalid
		</div>
	);
}
