// example/src/function-static/valid-12-classnames-function/example.tsx
import classNames from 'classnames';

/**
 * ✅ Valid: Using classNames() function
 * @validClasses [flex, items-center, justify-center]
 */
export function UsingClassNamesFunction() {
	return (
		<div className={classNames('flex', 'items-center', 'justify-center')}>
			Using classNames function
		</div>
	);
}

// example/src/vue/array-static/valid-12-array-in-classnames-function/example.vue
<script setup lang="ts">
import classNames from 'classnames';

// ✅ Valid: Array in classNames() function
// @validClasses [flex, items-center, justify-center]
</script>

<template>
  <div :class="classNames(['flex', 'items-center', 'justify-center'])">
  			Array in classNames()
  		</div>
</template>
