// example/src/vue/object-static/valid-16-object-mixed-with-array/example.vue
<script setup lang="ts">
import clsx from 'clsx';

const isActive = true;

// ✅ Valid: Mix of object and array
// @validClasses [flex, items-center, justify-center, bg-blue-500]
</script>

<template>
  <div
  			:class="clsx(['flex', 'items-center'], {
  				'justify-center': true,
  				'bg-blue-500': isActive
  			})">
  			Mixed with array
  		</div>
</template>

// example/src/jsx/array-ternary/valid-13-self-closing/example.tsx
import { clsx as cn } from 'clsx';

/**
 * ✅ Valid: Self-closing with ternary in array
 * @validClasses [rounded-lg, rounded-sm]
 */

const isActive = true;

export function ArrayTernarySelfClosingValid() {
	return <img className={cn([isActive ? 'rounded-lg' : 'rounded-sm'])} src="test.jpg" alt="test" />;
}
