// example/src/jsx/utility-function-imports/valid-08-namespace-import/example.tsx
/**
 * ✅ Valid: Namespace import with member expression
 * @utilityFunctions [{"name": "clsx", "from": "clsx"}]
 * @validClasses [flex, items-center, gap-4]
 */
import * as utils from 'clsx';

export function NamespaceImportValid() {
	return (
		<div className={utils.clsx('flex', 'items-center', 'gap-4')}>
			Namespace import with member expression
		</div>
	);
}

// example/src/vue/object-static/valid-16-object-mixed-with-array/example.vue
<script setup lang="ts">
import clsx from 'clsx';

const isActive = true;

// ✅ Valid: Mix of object and array
// @validClasses [flex, items-center, justify-center, bg-blue-500]
</script>

<template>
  <div
  			:class="clsx(['flex', 'items-center'], {
  				'justify-center': true,
  				'bg-blue-500': isActive
  			})">
  			Mixed with array
  		</div>
</template>
